# Generated by Django 2.1 on 2022-10-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('poster', models.CharField(max_length=3000)),
                ('duration', models.CharField(max_length=255)),
                ('grading', models.CharField(max_length=255)),
            ],
        ),
    ]
