# Generated by Django 2.1 on 2022-10-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moive',
            name='grading',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
